cc_library(
    name = "primary",
    hdrs = ["primary.hpp", "exceptions.hpp", "primary_helpers.hpp"],
    srcs = ["primary.cpp"],
    deps = ["@boost//:uuid"],
    visibility = ["//main:__pkg__", "//parser:__pkg__", "//test:__pkg__"],
)
