cc_library(
    name = "parser",
    hdrs = ["parser.hpp", "exceptions.hpp", "parser_helpers.hpp"],
    srcs = ["parser.cpp"],
    deps = ["//token:token"],
    visibility = ["//main:__pkg__", "//test:__pkg__"],
)
